### ISSUE TITLE
Second display producing garbled output

### ISSUE THREAD

**Issue by Gavriel94** [wern-apfel/Zenbook-UX481FA#1]
Hi Wern, hope you are well.

I recently picked up the same device (Zenbook-UX481FA). I have been closely following some online resources and found a thread where you posted an image of your device with both screens working. Are you able to commit the latest EFI folder? I am happy to test and provide feedback! Currently running macOS Monterey 12.3.1.

**Comment by wern-apfel** [comment]
Hi, I'm fine, thanks. Am pretty busy though, ATM I don't have an EFI fix for the Screenpad, but will commit when I have one.

**Comment by Gavriel94** [comment]
Thanks for your response Wern.
Even uploading enough for me to get the device as is in the screenshot you shared down below would be a great help and enough to get started.

![209643086-bb40fe65-c29b-4225-b743-d29d570b11ce](https://user-images.githubusercontent.com/45106732/212125027-723cd409-35c3-48b0-9c3e-dd7dda526425.jpg)

**Comment by wern-apfel** [comment]
I apologize for the delay. This project is currently on hold (due to lack of feedback) until I finish the others. But I will update it when I have more time

**Comment by Qonfused** [comment]
Tracking the issue here: https://github.com/acidanthera/bugtracker/issues/2243

**Comment by wern-apfel** [comment]
I no longer have this device, issue closed.
